/*
 * This source file was generated by the Gradle 'init' task
 */
package my.java.kafka.project;

import java.util.Properties;

import org.apache.kafka.clients.producer.Callback;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;
import org.apache.kafka.common.serialization.StringSerializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ProducerDemoWithKeys {

    private static final Logger log = LoggerFactory.getLogger(ProducerDemo.class);


    public static void main(String[] args) {
        System.out.println("System.out");
        System.err.println("System.err");

        log.error("ERROR");
        log.warn("WARN");
        log.info("INFO");
        log.debug("DEBUG");

        System.out.println(
            "defaultLogLevel = " +
            System.getProperty("org.slf4j.simpleLogger.defaultLogLevel")
        );

        Properties props = new Properties();

        // connecting to localhost 
        // would need additional props when making a secure connection to a hosted kafka cluster. i.e. amazon MSK
        // If Kafka is running from WSL, we will need to get its IP 
        // run 'hostname -I' in your wsl terminal to get the IP 
        // we will set the IP here for bootstrap.servers, but also in our config/server.properties file
        // it will look like: advertised.listeners=PLAINTEXT://172.22.70.39:9092 <- change will take affect on kafka restart 
        props.setProperty("bootstrap.servers", "172.22.70.39:9092");

        // setting props for our producer 
        props.setProperty("key.serializer", StringSerializer.class.getName());
        props.setProperty("value.serializer", StringSerializer.class.getName());

        // create the producer
        KafkaProducer<String, String> producer = new KafkaProducer<>(props);

        for(int j=0; j<2; j++){
            for(int i=0; i<10; i++){

            String topic = "demo_java_topic";
            String key = "id" + i;
            String value = "hello world " + i;


            // creat a producer record 
            ProducerRecord<String, String> producerRecord = new ProducerRecord<String,String>(topic, key, value);

            // send data
            producer.send(producerRecord, new Callback() {

                @Override
                public void onCompletion(RecordMetadata metadata, Exception e) {
                    
                    // executes everyime a record is sent or exception is thrown
                    if(e == null){
                        log.info("Key: " + key + " | Patition: " + metadata.partition());

                    } else {
                        log.error("Error while producing: ", e);
                    }
                }
            
            });

            try {
                Thread.sleep(500);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        }
        
        

        

        // flush and close the producer 
        producer.flush();

        // close actually flushes and then closes
        // I just included flush() to highlight it exists 
        producer.close();
    }
}
