-- Step 1
-- Run these in a folder called 'keys' WITH GIT BASH NOT POWERSHELL
-- openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -nocrypt
-- openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub 
-- Register the public key against the user for key-pair authentication
-- you get this value by opening up the pub file that we generated 
ALTER USER admin SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApHhh96Eqv5TPAjM/5qDF
BJ7ZAAajGYCo9BeI3VRgyFWTYlVluoMtQi9onXI/4NVUi3tenajxgx+2MgLDerz+
jBbCTfG7K0W2SWhIrNZR0HnXVBdt961MdWP3FApYgJkEef/3sIm2HNiHQVW7+Adr
ToeYP5AYUs/D+I9unDocqRQLZlxhofRsPEEw1i5+SpzCNouGnmT1ThhhfBv3rVlH
hsUonAwtymn5vpigethFffwBLptDWRs34beTAQV3eZBOJ7YhonmXn/bXJbNMXWBA
uU9IHTfIbSBKYNoZjltdGMaTWPMZxLts42Vg0jq+x7NU7yGKM44g0k4lS8WcDVjk
AwIDAQAB';

-- Step 2
-- Create the database and schema to house our streaming data
CREATE OR REPLACE DATABASE TRANSACTIONS_DB;
CREATE OR REPLACE SCHEMA TRANSACTIONS_SCHEMA;

-- Step 3
-- Create the target table for incoming streaming transactions
-- Each column maps directly to the fields generated by the Python client
CREATE OR REPLACE TABLE TRANSACTIONS_DB.TRANSACTIONS_SCHEMA.TRANSACTIONS (
    transaction_id  VARCHAR        NOT NULL,  -- Unique identifier for each transaction (UUID)
    sequence        NUMBER         NOT NULL,  -- Monotonically increasing offset token
    merchant        VARCHAR,                  -- Merchant name e.g. Amazon, Tesco
    amount          FLOAT,                    -- Transaction amount
    currency        VARCHAR(3),               -- ISO currency code e.g. GBP, USD, EUR
    status          VARCHAR(10),              -- approved, declined, or pending
    ts              TIMESTAMP_NTZ             -- UTC timestamp, no timezone offset stored
);

-- Step 4
-- See transactions.py in our course materials
-- Create a project structure like so:
-- projectFolder/.venv
-- projectFolder/transactions.py
-- projectFolder/<your_p8_file>
-- projectFolder/profile.json
-- You need to create a venv
-- Then pip install snowpipe-streaming to it
-- Your profile.json should look like this:
-- {
--     "user":"admin",
--     "account":"DVZTGXN-QF07017",
--     "url":"DVZTGXN-QF07017.snowflakecomputing.com",
--     "private_key_file":"rsa_key.p8",
--     "role":"accountadmin"
-- }
-- Best practices dictate a role with tighter security should really be used instead
-- We haven't covered security yet so we will just use accountadmin
-- Run the file: python3 transactions.py

-- Step 5
-- Query the table ordered by sequence to verify data is landing correctly
SELECT * FROM TRANSACTIONS_DB.TRANSACTIONS_SCHEMA.TRANSACTIONS ORDER BY SEQUENCE DESC;


-- Step 6
DROP DATABASE TRANSACTIONS_DB;