/*
 * This source file was generated by the Gradle 'init' task
 */
package my.java.kafka.project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        ProducerDemo classUnderTest = new ProducerDemo();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
